### ISSUE TITLE
lowercase/uppercase .ext and .EXT no longer differentiable

### ISSUE THREAD

**Issue by trapd00r** [trapd00r/LS_COLORS#116]
Just a heads up - we can no longer match uppercase and lowercase extensions differently, like so:

```
.pl 38;5;197
.PL 38;5;32
```

because of: https://github.com/coreutils/coreutils/pull/14

We can however match the entire filename like so:

`
*Makefile.PL  38;5;32
`

![pic](https://i.imgur.com/QfnkpCQ.png)

**Comment by rpdelaney** [comment]
So the tl;dr for us is that LS_COLORS is no longer case sensitive?

**Comment by trapd00r** [comment]
Probably, but are there many use cases where it's important? For me, personally, I think there's only one: and that's where perl makefiles always have an all uppercase PL extension which you normally never have in normal scripts.

**Comment by rpdelaney** [comment]
I think what I'm saying is maybe we should ignore this and pretend it didn't happen. So leave the `.PL` stuff in there. Otherwise, no I don't think it's significant, although offhand I think (for mysterious reasons) I'm more likely to see `.TXT` and `.JPG` uppercased than other extensions. ¯\\\_(ツ)_/¯

**Comment by trapd00r** [comment]
Ah, gotcha. Yeah, sure thing, was just a heads up if anyone (like me) relied on the differentiation. :)
