### ISSUE TITLE
README .dircolors vs LS_COLORS

### ISSUE THREAD

**Issue by godfrey-cw** [trapd00r/LS_COLORS#122]
The install instructions say 

```
wget https://raw.github.com/trapd00r/LS_COLORS/master/LS_COLORS -O $HOME/.dircolors
echo 'eval $(dircolors -b $HOME/.dircolors)' >> $HOME/.bashrc
. $HOME/.bashrc
```

Which is correct (it works). But the instruction above them says to add 

```
eval $( dircolors -b $HOME/LS_COLORS )
```
to the .bashrc, Which doesn't work, unless of course you pair it with 

```
wget https://raw.github.com/trapd00r/LS_COLORS/master/LS_COLORS -O $HOME/LS_COLORS
```

**Comment by rpdelaney** [comment]
Based on some user testing it seems the install instructions are still counter-intuitive. In the installation we refer to the file as `.dircolors` initially, which is confusing, because a user has not yet seen that in the next code block we download the file using `-O .dircolors`.

I think we should either:

1. rename the `LS_COLORS` file to `.dircolors`, or
2. use `LS_COLORS` consistently in the installation instructions.

**Comment by pickfire** [comment]
I think file should be named to `.dircolors`.

**Comment by dnedrow** [comment]
@pickfire It seems strange that the instructions rename the file to .dircolors. If you really want to hide the file, wouldn't `.LS_COLORS` make it easier for someone to find?

I think it would be far preferable to use LS_COLORS consistently in the documentation.

Additionally, @rpdelaney has suggested in another PR that shell files meant to be sourced should go under `.local/share`. That seems like the place LS_COLORS should go if anywhere.

My preference is `.LS_COLORS`. I don't like things be squirreled away under `.local`. I nearly always forget to look there when looking for sources.

**Comment by rpdelaney** [comment]
Consistency seems to make sense and it would be good to avoid overloading "dircolors" because we are not `dircolors`.

We can discuss where the file should go over in #136 but I think if you don't want to follow the XDG spec then you can edit the installation script or `export $XDG_DATA_HOME='$HOME'` in your local environment.

**Comment by dnedrow** [comment]
Fantastic.
