### ISSUE TITLE
Theme only works in /tmp/ on WSL

### ISSUE THREAD

**Issue by pcroland** [trapd00r/LS_COLORS#173]
![image](https://widevine.is-a.fail/V0TIM5.png)
It seems that the theme only works properly in `/tmp/LS_COLORS`. I think it's related to WSL because the theme does work properly on a linux server. Is there anything I can do to make it work? I tried modifying `/etc/profile` and `/etc/zsh/zshrc`  aswell but same results.
I'm using zsh with powerlevel10k.
Besides putting `zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}` in my `.zshrc` the installation shouldn't require anything else, right?

**Comment by rpdelaney** [comment]
On the bottom the executable bit is set in the filesystem everything. This is a common problem since Windows filesystems do not have a separate "executable" file mode like is present on Linux, so many drivers simply report that all files are executable (rather than none). I don't know of a way to handle this except to either (a) use a linux file system such as ext or (b) remove the executable style from your local LS_COLORS.

**Comment by trapd00r** [comment]
I think @rpdelaney summed it up nicely. Closing.
